/*=================================================================
 *
 * MATLABADDSAMPLE1
 * CPP Sample driver code for testOFECmatlab that calls a shared library created
 * using MATLAB Compiler SDK.
 * Refer to the MATLAB Compiler SDK documentation for more information.
 *
 *=================================================================*/
 // Include the library specific header file as generated by the 
 // MATLAB Compiler
#include <iostream>
#include "testOFECmatlab.h"

void MatlabAddSample()
{
	mxDouble aInData = 1.0;
	mwArray aIn(aInData);
	mxDouble bInData = 2.0;
	mwArray bIn(bInData);
	mwArray cOut;
	try
	{
		MatlabAdd(1, cOut, aIn, bIn);
		std::cout << cOut << std::endl;
	}
	catch (const mwException& e)
	{
		std::cerr << e.what() << std::endl;
	}
	catch (...)
	{
		std::cerr << "Unexpected error thrown" << std::endl;
	}
}
void matlabDrawSample()
{
	try
	{
		matlabDraw();
	}
	catch (const mwException& e)
	{
		std::cerr << e.what() << std::endl;
	}
	catch (...)
	{
		std::cerr << "Unexpected error thrown" << std::endl;
	}
}



TEST_CASE("utility_matlab", "[matlab]")
{
	MatlabAddSample();
	matlabDrawSample();
}


